export enum ErrorCode {
    ERR_INVALID_PARAM = 'ERR_INVALID_PARAM',
    ERR_DUPLICATED_PARAM = 'ERR_DUPLICATED_PARAM',
    ERR_INVALID_ACCESS = 'ERR_INVALID_ACCESS',
    ERR_STORE_NOT_FOUND = 'ERR_STORE_NOT_FOUND',
    ERR_CUSTOM_FIELD_NOT_FOUND = 'ERR_CUSTOM_FIELD_NOT_FOUND',
    ERR_CUSTOMER_NOT_FOUND = 'ERR_CUSTOMER_NOT_FOUND',
    ERR_PRODUCT_NOT_FOUND = 'ERR_PRODUCT_NOT_FOUND',
    ERR_ORDER_NOT_FOUND = 'ERR_ORDER_NOT_FOUND',
    ERR_FORGERY_DATA = 'ERR_FORGERY_DATA',
    ERR_STORE_ALREADY_EXISTS = 'ERR_STORE_ALREADY_EXISTS',
    ERR_CUSTOMER_ALREADY_EXISTS = 'ERR_CUSTOMER_ALREADY_EXISTS',
    ERR_INTERNAL_SERVER = 'ERR_INTERNAL_SERVER',
}
